### ISSUE TITLE
Error when creating wallet

### ISSUE THREAD

**Issue by cryptoB0T** [fun-xyz/funkit-react#24] opened 2023-09-20 20:39 UTC
unable to create a wallet. getting this error:

```
ERROR
bad request {"errorMsg":"Invalid request: Not enough group information is provided and group is not found.","errorCode":"InvalidParameterError","reqId":"dbd69262-4515-452a-b333-490d8874f33a"}

check the api call parameters. its mostly because some call parameters are wrong
Docs: https://docs.fun.xyz
Discord: https://discord.gg/mvQunrx6NG

Trace:
Error: bad request {"errorMsg":"Invalid request: Not enough group information is provided and group is not found.","errorCode":"InvalidParameterError","reqId":"dbd69262-4515-452a-b333-490d8874f33a"}

check the api call parameters. its mostly because some call parameters are wrong
Docs: https://docs.fun.xyz
Discord: https://discord.gg/mvQunrx6NG

Trace:
    at https://mctcrj-3000.csb.app/static/js/bundle.js:30207:15
    at async sendPostRequest (https://mctcrj-3000.csb.app/static/js/bundle.js:30255:10)
    at async executeOp (https://mctcrj-3000.csb.app/static/js/bundle.js:27185:10)
    at async FunWallet.executeOperation (https://mctcrj-3000.csb.app/static/js/bundle.js:31985:17)
    at async createWallet (https://mctcrj-3000.csb.app/static/js/bundle.js:92:21)
```

this happens when invoking: 
```
funWallet.executeOperation(auth, op)
```

steps to reproduce: 

1. clone repo 
2. `npm i && npm start`
3. see this line: https://github.com/fun-xyz/Social-Web-Demo/blob/main/src/app.js#L77

now this same code works in codesandbox, so might have something to do with the dependencies? 

also, if you try to fork the codesandbox and rebuild it, you will see the same error. here's a [fork of the repo](https://codesandbox.io/p/github/cryptoB0T/Social-Web-Demo/main?file=%2Fsrc%2Fapp.js%3A93%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clms72d3w00a93b6i25y2b7ox%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clms72d3w00a53b6i4m1jvmue%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clms72d3w00a73b6i4d7vr7gt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clms72d3w00a83b6iilyknvlg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clms72d3w00a53b6i4m1jvmue%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clms72d3w00a43b6i4o0an3i1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.js%2522%257D%255D%252C%2522id%2522%253A%2522clms72d3w00a53b6i4m1jvmue%2522%252C%2522activeTabId%2522%253A%2522clms72d3w00a43b6i4o0an3i1%2522%257D%252C%2522clms72d3w00a83b6iilyknvlg%2522%253A%257B%2522id%2522%253A%2522clms72d3w00a83b6iilyknvlg%2522%252C%2522activeTabId%2522%253A%2522clms73xp100vf3b6igqw4mqbe%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clms73xp100vf3b6igqw4mqbe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clms72d3w00a73b6i4d7vr7gt%2522%253A%257B%2522id%2522%253A%2522clms72d3w00a73b6i4d7vr7gt%2522%252C%2522activeTabId%2522%253A%2522clms72d3w00a63b6ijm4pptdm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clms72d3w00a63b6ijm4pptdm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clms72d6n000he4j142iu528r%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clms73ttj00r63b6i3l2g9s5n%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by cryptoB0T** [comment] 2023-09-21 15:18
I have some clues as to the issue. it appears we're not properly constructing the signature.

**Comment by cryptoB0T** [comment] 2023-09-21 15:37
the `userOp.signature` should be padded. for some reason this is not properly formed. 

valid: 
```
'0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000003f3b4fa62289881c7b87bf8e8ab6d3d3f40547430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000412a334f6fcb57bd0d9cf8f09f5ea3e2aa3eac10606bab6b33475f40d68dcb5b34604a27ac8d4b3523571c67dc594b0bac09b0200d3173ed1b57cb4601d663acde1c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
```

invalid
```
"0x13aa1bee308c48eae46380a7d52cc328f4f48390a3b5071a41f7e3949b2b496400a2f4132ca5a98672ccaf5c3106bd1cfe1d25d8756b971b765595f305e43b731b"
```

the problem may be that we're constructing an invalid signature

**Comment by Chazzzzzzz** [comment] 2023-09-21 20:47
The issue is that this particular operation is mistakenly treated as a multi-sig operation.

The issue is known and should be fixed by this PR: 
https://github.com/fun-xyz/funkit-core/pull/366/files#diff-e0dbba56ff4e28ac762c8f1c68acb3b69eb5ff6bc0f2036016f11cc637325669

Will do a release soon to fix it

**Comment by Chazzzzzzz** [comment] 2023-09-21 21:28
A new version of @funkit/react is released https://www.npmjs.com/package/@funkit/react

verified that the issue is fixed https://codesandbox.io/p/github/fun-xyz/Social-Web-Demo/main?file=/src/app.js:1,1

**Closed by Chazzzzzzz** 2023-09-21 21:28 UTC

**Comment by cryptoB0T** [comment] 2023-09-22 07:57
@Chazzzzzzz when i tested this it worked with the padded signature, but not the non-padded signature. can you point to where in the code i can learn more about how this became mistakenly treated as a multi-sig?
